// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDefghIJKLMNOPQRSTUVWXYZabcdefg',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'fikkk-b802d',
    authDomain: 'fikkk-b802d.firebaseapp.com',
    storageBucket: 'fikkk-b802d.appspot.com',
    measurementId: 'G-1FDB3GK22H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefghIJKLMNOPQRSTUVWXYZabcdefg',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'fikkk-b802d',
    storageBucket: 'fikkk-b802d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDefghIJKLMNOPQRSTUVWXYZabcdefg',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'fikkk-b802d',
    authDomain: 'fikkk-b802d.firebaseapp.com',
    storageBucket: 'fikkk-b802d.appspot.com',
    measurementId: 'G-1FDB3GK22H',
  );

}