// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyoDnf-AcP8bvL3-DjW8VFRn39JYbA9yU',
    appId: '1:864093639820:web:abcdef1234567890',
    messagingSenderId: '864093639820',
    projectId: 'fikkk-b802d',
    authDomain: 'fikkk-b802d.firebaseapp.com',
    storageBucket: 'fikkk-b802d.appspot.com',
    measurementId: 'G-1FDB3GK22H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyoDnf-AcP8bvL3-DjW8VFRn39JYbA9yU',
    appId: '1:864093639820:android:874c6fbe452b9f993457a9',
    messagingSenderId: '864093639820',
    projectId: 'fikkk-b802d',
    storageBucket: 'fikkk-b802d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyoDnf-AcP8bvL3-DjW8VFRn39JYbA9yU',
    appId: '1:864093639820:web:abcdef1234567890',
    messagingSenderId: '864093639820',
    projectId: 'fikkk-b802d',
    authDomain: 'fikkk-b802d.firebaseapp.com',
    storageBucket: 'fikkk-b802d.appspot.com',
    measurementId: 'G-1FDB3GK22H',
  );

}
