// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCao6--DJNBJEQkAtNrI7jJWNr15XpHVA4',
    appId: '1:864093639820:web:6be932aff4b966eb3457a9',
    messagingSenderId: '864093639820',
    projectId: 'fikkk-b802d',
    authDomain: 'fikkk-b802d.firebaseapp.com',
    storageBucket: 'fikkk-b802d.firebasestorage.app',
    measurementId: 'G-1FDB3GK22H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyoDnf-AcP8bvL3-DjW8VFRn39JYbA9yU',
    appId: '1:864093639820:android:874c6fbe452b9f993457a9',
    messagingSenderId: '864093639820',
    projectId: 'fikkk-b802d',
    storageBucket: 'fikkk-b802d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7r7inRDaqD4rsFeUofsEzXmy_xyeOTs',
    appId: '1:864093639820:ios:2acd4a6f1947993d3457a9',
    messagingSenderId: '864093639820',
    projectId: 'fikkk-b802d',
    storageBucket: 'fikkk-b802d.firebasestorage.app',
    iosClientId: '864093639820-ieij97moja5frt9ajq45plmb9po6lrgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7r7inRDaqD4rsFeUofsEzXmy_xyeOTs',
    appId: '1:864093639820:ios:2acd4a6f1947993d3457a9',
    messagingSenderId: '864093639820',
    projectId: 'fikkk-b802d',
    storageBucket: 'fikkk-b802d.firebasestorage.app',
    iosClientId: '864093639820-ieij97moja5frt9ajq45plmb9po6lrgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCao6--DJNBJEQkAtNrI7jJWNr15XpHVA4',
    appId: '1:864093639820:web:6be932aff4b966eb3457a9',
    messagingSenderId: '864093639820',
    projectId: 'fikkk-b802d',
    authDomain: 'fikkk-b802d.firebaseapp.com',
    storageBucket: 'fikkk-b802d.firebasestorage.app',
    measurementId: 'G-1FDB3GK22H',
  );

}